"""
Logs in console
"""
import src.constans.COLORS as COLORS

LOG_INIT = f"{COLORS.WHITE}{COLORS.MAGENTA_BG}{COLORS.BOLD}KIRBY{COLORS.RESET}{COLORS.WHITE}{COLORS.BOLD}-{COLORS.RESET}{COLORS.GREEN}[INFO]:{COLORS.RESET}{COLORS.YELLOW} 200 {COLORS.RESET}{COLORS.GREEN}Bot iniciado."

LOG_ERROR = f"{COLORS.WHITE}{COLORS.MAGENTA_BG}{COLORS.BOLD}KIRBY{COLORS.RESET}{COLORS.WHITE}{COLORS.BOLD}-{COLORS.RESET}{COLORS.GREEN}[INFO]:{COLORS.RESET}{COLORS.RED} 500 {COLORS.RESET}{COLORS.BLUE}Comando no ejecutado."

LOG_200 = f"{COLORS.WHITE}{COLORS.MAGENTA_BG}{COLORS.BOLD}KIRBY{COLORS.RESET}{COLORS.WHITE}{COLORS.BOLD}-{COLORS.RESET}{COLORS.GREEN}[INFO]:{COLORS.RESET}{COLORS.YELLOW} 200 {COLORS.RESET}{COLORS.CYAN}Comando ejecutado."
